Repository paradigmxyz/alphanet, pull requests merged in 2024-10, with the labels that each got.

#130 chore: spin up 2 nodes by default
  etc/kurtosis.yaml
Labels: C-test

#128 feat: wallet crate
  Cargo.lock
  Cargo.toml
  crates/wallet/Cargo.toml
  crates/wallet/src/lib.rs
Labels: C-enhancement

#137 chore(cli): use reth_cli_util allocator
  Cargo.lock
  bin/alphanet/Cargo.toml
  bin/alphanet/src/main.rs
Labels: C-enhancement, A-cli

#129 feat: impl `wallet_` namespace
  Cargo.lock
  Cargo.toml
  bin/alphanet/Cargo.toml
  bin/alphanet/src/main.rs
  clippy.toml
  crates/wallet/Cargo.toml
  crates/wallet/src/lib.rs
Labels: C-enhancement

#141 chore: wrap inner
  crates/wallet/src/lib.rs
Labels: C-enhancement

#142 feat: add permit
  Cargo.lock
  crates/wallet/Cargo.toml
  crates/wallet/src/lib.rs
Labels: C-enhancement

#147 chore: tune network settings
  Cargo.lock
  Cargo.toml
  crates/node/Cargo.toml
  crates/node/src/node.rs
Labels: C-enhancement

#152 fix: set max fee per gas correctly
  crates/wallet/src/lib.rs
Labels: C-bug

#153 fix: set `GIT_TAG` in Makefile
  Makefile
Labels: C-bug

#154 chore: bump fees
  crates/wallet/src/lib.rs
Labels: C-enhancement
