Repository paradigmxyz/alphanet, pull requests merged in 2024-09, with the labels that each got.

#110 feat: kurtosis instructions
  README.md
  etc/kurtosis.yaml
Labels: A-docs

#111 chore: bump reth
  Cargo.lock
  Cargo.toml
  bin/alphanet/Cargo.toml
  bin/alphanet/src/main.rs
  crates/node/Cargo.toml
  crates/node/src/evm.rs
  crates/node/src/lib.rs
  crates/node/src/node.rs
  crates/precompile/Cargo.toml
  crates/precompile/src/secp256r1.rs
  crates/testing/Cargo.toml
Labels: C-enhancement

#112 feat: activate prague always
  Cargo.lock
  Cargo.toml
  Dockerfile
  bin/alphanet/src/main.rs
  crates/node/Cargo.toml
  crates/node/src/chainspec.rs
  crates/node/src/evm.rs
  crates/node/src/lib.rs
  crates/node/src/node.rs
  crates/precompile/Cargo.toml
  crates/precompile/src/secp256r1.rs
  crates/testing/Cargo.toml
Labels: C-enhancement

#115 fix: prague payload building
  Cargo.lock
  Cargo.toml
  bin/alphanet/Cargo.toml
  bin/alphanet/src/main.rs
  crates/node/Cargo.toml
  crates/node/src/chainspec.rs
  crates/node/src/evm.rs
  crates/node/src/node.rs
  crates/precompile/src/secp256r1.rs
Labels: C-bug

#107 feat: launch with experimental engine
  Cargo.lock
  Cargo.toml
  bin/alphanet/Cargo.toml
  bin/alphanet/src/main.rs
Labels: C-enhancement

#116 chore: pin to reth v1.0.7
  Cargo.lock
  Cargo.toml
  bin/alphanet/src/main.rs
Labels: C-enhancement

#119 chore: remove unused testing modules
  crates/testing/src/lib.rs
  crates/testing/src/test_suite.rs
  crates/testing/src/wallet.rs
Labels: C-enhancement

#117 fix: use alphanet chain id
  crates/node/src/chainspec.rs
Labels: C-bug

#120 feat: fund accounts on devnet
  crates/node/src/chainspec.rs
  etc/dev-genesis.json
Labels: C-enhancement

#122 fix: include dev genesis in dockerfile
  .dockerignore
  Dockerfile
Labels: C-bug

#121 fix: set chain id and block time in kurtosis
  etc/kurtosis.yaml
Labels: C-bug

#124 fix: push tag and latest for non-alpha versions
  .github/workflows/docker.yml
Labels: C-bug
